// Reads web/dist/_app/manifest.txt (written by esbuild) and emits a Rust
// module with `app_asset_for(name)` plus `NAME_*` constants — the hashed
// filenames change every web build, so the table can't live in source.

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::exit;

const REQUIRED_TOP: &[&str] = &["index.html", "about.html", "privacy.html", "favicon.svg", "og.png"];
const REQUIRED_KEYS: &[&str] = &["main_js", "main_css", "wasm_bg"];

fn gate_fail(reason: &str) -> ! {
    eprintln!(
        "\nshout-server build gate: web/dist/ {reason}\n\
         run `just web-build` from the repo root before building the server.\n"
    );
    exit(1);
}

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let dist = manifest_dir.join("../web/dist");
    let dist_app = dist.join("_app");
    let manifest_path = dist_app.join("manifest.txt");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", dist.display());
    println!("cargo:rerun-if-changed={}", dist_app.display());

    let missing_top: Vec<&str> = REQUIRED_TOP
        .iter()
        .copied()
        .filter(|f| !dist.join(f).exists())
        .collect();
    if !missing_top.is_empty() {
        gate_fail(&format!("missing top-level files {missing_top:?}"));
    }
    if !manifest_path.exists() {
        gate_fail("missing _app/manifest.txt");
    }

    let manifest = match read_manifest(&manifest_path) {
        Ok(m) => m,
        Err(e) => gate_fail(&format!("can't read {}: {e}", manifest_path.display())),
    };
    let missing_keys: Vec<&str> = REQUIRED_KEYS
        .iter()
        .copied()
        .filter(|k| !manifest.contains_key(*k))
        .collect();
    if !missing_keys.is_empty() {
        gate_fail(&format!(
            "{} missing keys {missing_keys:?}",
            manifest_path.display()
        ));
    }

    let mut entries: Vec<PathBuf> = fs::read_dir(&dist_app)
        .unwrap_or_else(|e| panic!("read {}: {e}", dist_app.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_file() && p.file_name() != Some("manifest.txt".as_ref()))
        .collect();
    entries.sort();

    let mut arms = String::new();
    for path in &entries {
        let file_name = path.file_name().unwrap().to_string_lossy().to_string();
        let ctype = ctype_for(&file_name).unwrap_or_else(|| {
            panic!("unknown asset extension: {}", path.display());
        });
        println!("cargo:rerun-if-changed={}", path.display());
        arms.push_str(&format!(
            "        {name:?} => (include_bytes!({path:?}), {ctype:?}),\n",
            name = file_name,
            path = path.to_string_lossy(),
        ));
    }

    let body = format!(
        r#"// Generated by shout-server/build.rs — do not edit.

pub const NAME_MAIN_JS: &str = {main_js:?};
pub const NAME_MAIN_CSS: &str = {main_css:?};
pub const NAME_WASM_BG: &str = {wasm_bg:?};

pub fn app_asset_for(name: &str) -> Option<(&'static [u8], &'static str)> {{
    Some(match name {{
{arms}        _ => return None,
    }})
}}
"#,
        main_js = manifest["main_js"],
        main_css = manifest["main_css"],
        wasm_bg = manifest["wasm_bg"],
    );

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("assets_gen.rs");
    fs::write(&out_path, body).expect("write assets_gen.rs");
}

fn read_manifest(path: &Path) -> std::io::Result<HashMap<String, String>> {
    let text = fs::read_to_string(path)?;
    Ok(text
        .lines()
        .filter_map(|line| {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                return None;
            }
            line.split_once('=').map(|(k, v)| (k.trim().to_string(), v.trim().to_string()))
        })
        .collect())
}

fn ctype_for(name: &str) -> Option<&'static str> {
    let ext = name.rsplit('.').next()?;
    Some(match ext {
        "js" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "wasm" => "application/wasm",
        _ => return None,
    })
}
