// Reads `web/dist/_app/manifest.txt` (written by esbuild — see
// web/esbuild.config.mjs) to learn which content-hashed filenames map to
// each canonical asset, then emits a Rust module that include_bytes!() each
// hashed file and exposes `app_asset_for(name)` plus `NAME_*` constants.
// Generating this matters because esbuild changes the hashed names every
// build, so server.rs can't include_bytes! them by literal path.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::exit;

fn main() {
    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let dist = manifest_dir.join("../web/dist");
    let dist_app = dist.join("_app");
    let manifest_path = dist_app.join("manifest.txt");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", dist.display());
    println!("cargo:rerun-if-changed={}", dist_app.display());

    let required_top = ["index.html", "about.html", "privacy.html", "favicon.svg", "og.png"];
    let missing_top: Vec<&str> = required_top
        .iter()
        .copied()
        .filter(|f| !dist.join(f).exists())
        .collect();
    if !missing_top.is_empty() || !manifest_path.exists() {
        eprintln!(
            "\nshout-server build gate: web/dist/ incomplete (missing {missing_top:?} or _app/manifest.txt)\n\
             run `just web-build` from the repo root before building the server.\n"
        );
        exit(1);
    }

    let manifest = read_manifest(&manifest_path);
    let main_js = manifest_get(&manifest, "main_js", &manifest_path);
    let main_css = manifest_get(&manifest, "main_css", &manifest_path);
    let wasm_bg = manifest_get(&manifest, "wasm_bg", &manifest_path);

    let mut entries: Vec<PathBuf> = fs::read_dir(&dist_app)
        .unwrap_or_else(|e| panic!("read {}: {e}", dist_app.display()))
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_file() && p.file_name() != Some("manifest.txt".as_ref()))
        .collect();
    entries.sort();

    let mut arms = String::new();
    for path in &entries {
        let file_name = path.file_name().unwrap().to_string_lossy().to_string();
        let ctype = ctype_for(&file_name).unwrap_or_else(|| {
            panic!("unknown asset extension: {}", path.display());
        });
        println!("cargo:rerun-if-changed={}", path.display());
        let abs = path
            .canonicalize()
            .unwrap_or_else(|e| panic!("canonicalize {}: {e}", path.display()));
        arms.push_str(&format!(
            "        {name:?} => (include_bytes!({path:?}), {ctype:?}),\n",
            name = file_name,
            path = abs.to_string_lossy(),
        ));
    }

    let body = format!(
        r#"// Generated by shout-server/build.rs — do not edit.

pub const NAME_MAIN_JS: &str = {main_js:?};
pub const NAME_MAIN_CSS: &str = {main_css:?};
pub const NAME_WASM_BG: &str = {wasm_bg:?};

pub fn app_asset_for(name: &str) -> Option<(&'static [u8], &'static str)> {{
    Some(match name {{
{arms}        _ => return None,
    }})
}}
"#
    );

    let out_path = PathBuf::from(env::var("OUT_DIR").unwrap()).join("assets_gen.rs");
    fs::write(&out_path, body).expect("write assets_gen.rs");
}

fn read_manifest(path: &Path) -> Vec<(String, String)> {
    let text = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
    text.lines()
        .filter_map(|line| {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                return None;
            }
            line.split_once('=')
                .map(|(k, v)| (k.trim().to_string(), v.trim().to_string()))
        })
        .collect()
}

fn manifest_get(manifest: &[(String, String)], key: &str, path: &Path) -> String {
    manifest
        .iter()
        .find(|(k, _)| k == key)
        .map(|(_, v)| v.clone())
        .unwrap_or_else(|| panic!("{}: missing key {key:?}", path.display()))
}

fn ctype_for(name: &str) -> Option<&'static str> {
    let ext = name.rsplit('.').next()?;
    Some(match ext {
        "js" => "text/javascript; charset=utf-8",
        "css" => "text/css; charset=utf-8",
        "wasm" => "application/wasm",
        _ => return None,
    })
}
